<?php

 /** var \Magento\Framework\View\Element\Template @block */
?>
<form data-mage-init='{"validation": {} }'>
    <div class="control">
        <input type="text"
               name="email" id="email" class="input-text"
               placeholder="<?= __('Your Email') ?>"
               data-validate="{required: true, 'validate-email': true}"
        />
    </div>
    <button type="submit" class="acton primary"><?= __('Your Email') ?></button>
</form>
<br/>
<script type="text/x-magento-init">
    {
      "#target": {
        "mage2tvjs_coffee": {
          "base_url" : "<?= $block->escapeJs($block->getBaseUrl()); ?>"
        }
      }
    }
</script>
<pre>
    <div id="target"></div>
    <div id="target_inline" data-mage-init='{"Mage2tv_Js/js/requirejs-example": {"base_url": "/"}}'></div>
</pre>
