<?php

 /** var \Magento\Framework\View\Element\Template @block */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "exampleUiComponent": {
                        "component": "Mage2tv_Js/js/plain-view-model-kotrack"
                    }
                }
            }
        }
    }
</script>
<div data-bind="scope: 'exampleUiComponent'">
   <h3 data-bind="text: label"></h3>
    <table data-bind="foreach: items">
        <tr>
            <td data-bind="text: name"></td>
            <td data-bind="text: qty"></td>
            <td data-bind="text: price"></td>
            <td data-bind="text: $parent.rowTotal($data)"></td>
        </tr>
    </table>
    <div>Additional charge: <span data-bind="text: additional_charge"></span></div>
    <strong>Total: <span data-bind="text: total()"></span></strong>
</div>