<?php

 /** var \Magento\Framework\View\Element\Template @block */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "startSimple": {
                        "component": "Mage2tv_Js/js/plain-view-model",
                        "base_url": "<?= $block->escapeJs($block->getBaseUrl()) ?>"
                    }
                }
            }
        }
    }
</script>
<div data-bind="scope: 'startSimple'">
    <h2 data-bind="text: title"></h2>
    <pre data-bind="text: JSON.stringify(config, null, 2)"></pre>
    <pre data-bind="text: output"></pre>
</div>